# Generated by Django 6.0.2 on 2026-02-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Primary domain for the panel.', max_length=255, verbose_name='Domain')),
                ('panel_port', models.PositiveIntegerField(help_text='External port where the panel is available.', verbose_name='Panel port')),
                ('hysteria_port', models.PositiveIntegerField(help_text='Port used by the Hysteria server.', verbose_name='Hysteria port')),
                ('masquerade_url', models.URLField(help_text='Site URL used for Hysteria masquerade.', verbose_name='Masquerade site')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Panel settings',
                'verbose_name_plural': 'Panel settings',
            },
        ),
    ]
