# Generated by Django 6.0.2 on 2026-02-08 20:39

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsettings',
            name='hysteria_port',
            field=models.PositiveIntegerField(help_text='Port used by the Hysteria server.', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535), core.validators.validate_safe_port], verbose_name='Hysteria port'),
        ),
        migrations.AlterField(
            model_name='panelsettings',
            name='panel_port',
            field=models.PositiveIntegerField(help_text='External port where the panel is available.', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535), core.validators.validate_safe_port], verbose_name='Panel port'),
        ),
    ]
