# Generated by Django 6.0.2 on 2026-02-08 21:17

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_panelsettings_hysteria_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsettings',
            name='hysteria_port',
            field=models.PositiveIntegerField(default=7443, help_text='Port used by the Hysteria server.', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535), core.validators.validate_safe_port], verbose_name='Hysteria port'),
        ),
        migrations.AlterField(
            model_name='panelsettings',
            name='masquerade_url',
            field=models.URLField(default='https://www.google.com', help_text='Site URL used for Hysteria masquerade.', verbose_name='Masquerade site'),
        ),
        migrations.AlterField(
            model_name='panelsettings',
            name='panel_port',
            field=models.PositiveIntegerField(default=8888, help_text='External port where the panel is available.', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535), core.validators.validate_safe_port], verbose_name='Panel port'),
        ),
    ]
