# Generated by Django 6.0.2 on 2026-02-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('upload_limit_mbps', models.PositiveIntegerField(default=0)),
                ('download_limit_mbps', models.PositiveIntegerField(default=0)),
                ('traffic_limit_gb', models.PositiveIntegerField(default=0)),
                ('traffic_used_gb', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
