# Generated by Django 6.0.2 on 2026-02-05 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update time.', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation time.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='download_limit_mbps',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited download speed.', verbose_name='Download limit (Mbps)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Leave empty for no expiration.', null=True, verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive clients cannot connect.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(help_text='Letters and digits only.', max_length=128, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Only letters and digits are allowed.'), django.core.validators.MinLengthValidator(8)], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='client',
            name='traffic_limit_gb',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited traffic.', verbose_name='Traffic limit (GB)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='traffic_used_gb',
            field=models.PositiveIntegerField(default=0, help_text='Total traffic used by the client.', verbose_name='Traffic used (GB)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='upload_limit_mbps',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited upload speed.', verbose_name='Upload limit (Mbps)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(help_text='Letters and digits only.', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Only letters and digits are allowed.'), django.core.validators.MinLengthValidator(4)], verbose_name='Username'),
        ),
    ]
