# Generated by Django 6.0.2 on 2026-02-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(default='Config', help_text='', max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='client',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Leave empty for no expiration.', null=True, verbose_name='Expires at'),
        ),
    ]
