# Generated by Django 6.0.2 on 2026-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_title_alter_client_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, default='Config', help_text='Display name for this configuration.', max_length=64, verbose_name='Title'),
        ),
    ]
